[project]
name = "artle"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
litestar = ">=2.9.1,<3"
uvicorn = ">=0.30.3,<0.31"
jinja2 = ">=3.1.4,<4"
polars = ">=1.2.1,<2"
